// The MIT License (MIT)

// Copyright (c) 2019 Caili Li

//  Permission is hereby granted, free of charge, to any person obtaining a
//  copy of this software and associated documentation files (the "Software"),
//  to deal in the Software without restriction, including without limitation
//  the rights to use, copy, modify, merge, publish, distribute, sublicense,
//  and/or sell copies of the Software, and to permit persons to whom the
//  Software is furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
//  OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.

/* code */

#include "ContourPlot.hpp"

namespace roboflow
{
namespace contour
{

ContourPlot::ContourPlot()
{
    double limits[4] = {-1, 1, -1, 1};
    std::vector<double> planes =
        {0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0,
         1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0};
    contour_.SetLimits(limits);
    contour_.SetPlanes(planes);
    contour_.SetFirstGrid(256, 256);
    contour_.SetSecondaryGrid(1024, 1024);
    contour_.SetFieldFcn(Jonathan::TestFunction);
}

void ContourPlot::draw(BLContext &ctx)
{
    using Jonathan::CLineStrip;
    using Jonathan::CLineStripList;

    // Plotting strip generated by CLineStripList
    // generating info
    contour_.Generate();

    // draw line strips
    CLineStripList *pStripList;
    CLineStrip *pStrip;
    uint32_t i, index;
    CLineStripList::iterator pos;
    CLineStrip::iterator pos2;
    double pLimits[4];
    double x, y;

    contour_.GetLimits(pLimits);
    for (i = 0; i < contour_.GetNPlanes(); i++)
    {
        BLPath path;
        pStripList = contour_.GetLines(i);
        for (pos = pStripList->begin(); pos != pStripList->end(); pos++)
        {
            pStrip = (*pos);
            if (pStrip->empty())
                continue;

            // putting point at start and end of strip
            // retreiving index
            bool is_first = true;
            for (auto index : *pStrip)
            {
                x = contour_.GetXi(index);
                y = contour_.GetYi(index);
                if (is_first)
                {
                    path.moveTo(x, y);
                    is_first = false;
                }
                else
                {
                    path.lineTo(x, y);
                }
            }
        }
        ctx.strokePath(path);
    }
}

} // namespace contour
} // namespace roboflow
